### ISSUE TITLE
安裝後自動消失

### ISSUE THREAD

**Issue by kennedy0527** [aaaddress1/madPocket#5]
我resign完 透過iTunes 安裝ipa

在手機上看得到 app安裝 

不過 安裝完它就消失了...

這是什麼問題？

該怎麼解決？

謝謝

**Comment by abcde134256** [comment]
我也有一樣問題
有用iOS APP Signer選自己帳號輸出ipa了
但是用iTune裝完它就直接消失
用Xcode裝會說The application could not be verified.
請問是哪邊出問題了嗎？
謝謝

**Comment by abcde134256** [comment]
還是一定要花99鎂才可以安裝？

**Comment by kennedy0527** [comment]
成功安裝了....
iOS app signer 要選 Provisioning Profile
